### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by liorsu** [AlexanderBabel/homebridge-broadlink-rm#53]
Hello,
I experience random crashes with the following stack trace-

[11/14/2019, 9:49:10 PM] [Broadlink RM] Learn Code (ready)
[11/14/2019, 9:49:15 PM] TypeError: log is not a function
    at stop (/homebridge/node_modules/homebridge-broadlink-rm-tv/helpers/learnData.js:14:3)
    at Object.start (/homebridge/node_modules/homebridge-broadlink-rm-tv/helpers/learnData.js:18:3)
    at LearnIRAccessory.toggleLearning (/homebridge/node_modules/homebridge-broadlink-rm-tv/accessories/learnCode.js:41:17)
    at Characteristic.On.emit (events.js:210:5)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) 

[11/14/2019, 9:49:15 PM] Got SIGTERM, shutting down Homebridge...
[11/14/2019, 9:49:24 PM] Loaded config.json with 0 accessories and 3 platforms.

**Comment by kiwi-cam** [comment]
Thanks for the information. I've taken a quick look and the line numbers don't match with the call that's failing. I'll be able to investigate further when I get home - it's been a while since I've used the learn code functionality.  Could you just confirm that you're running the latest version - or let me know what version you're running?

**Comment by liorsu** [comment]
yes, it is the latest version
just installed it today

**Comment by kiwi-cam** [comment]
Is there anything in particular you're doing when it crashes? It looks like it's trying to learn codes when it crashes, but I can't recreate the problem on my device.

**Comment by liorsu** [comment]
I think that it happened when I accidentally did learn on two different devices

**Comment by kiwi-cam** [comment]
Are you able to do some testing and confirm? It'd be great if you could identify steps that consistently recreate the error.
Unfortunately if it's related to two broadlink devices then it's not a situation I can recreate so I'm not sure I'll be able to do much about this one.
